#!/bin/bash
git submodule add git@github.com:IORoot/wp-plugin__acf--codemirror.git;
git submodule add git@github.com:IORoot/wp-plugin__acf-options-import-export.git;
git submodule add git@github.com:IORoot/wp-plugin__acf--inline-datetime-field.git;
git submodule add git@github.com:IORoot/wp-plugin__acf--inline-datetime-field.git;
git submodule add git@github.com:IORoot/wp-plugin__oauth.git;
git submodule add git@github.com:IORoot/wp-plugin__admin--remove-comments.git;
git submodule add git@github.com:IORoot/wp-plugin__admin-themes.git;
git submodule add git@github.com:IORoot/wp-plugin__cpt--pulse.git;
git submodule add git@github.com:IORoot/wp-pluging__menu--code-inject.git;
git submodule add git@github.com:IORoot/wp-plugin__page-builder.git;
git submodule add git@github.com:IORoot/wp-plugin__page-builder--flickity.git;
git submodule add git@github.com:IORoot/wp-plugin__page-builder--rawcode.git;
git submodule add git@github.com:IORoot/wp-plugin__page-builder--yt-lite.git;
git submodule add git@github.com:IORoot/wp-plugin__api-scraper.git;
git submodule add git@github.com:IORoot/wp-plugin__ytdl.git;
git submodule add git@github.com:IORoot/wp-plugin__andyp-plugins.git;
git submodule add git@github.com:IORoot/wp-plugin__thumbnail-folders.git;
git submodule add git@github.com:IORoot/wp-plugin__footer.git;